on: push

name: ðŸš€ Deploy website on push

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ðŸ“¦ Install npm dependencies
        run: npm install

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp-quaiantiqueprffe.alwaysdata.net
          username: quaiantiqueprffe
          password: ${{ secrets.ftp_password }}

          protocol: ftps
          port: 21
          timeout: 60000

          server-dir: /www/
          local-dir: ./

          log-level: verbose

          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules**
            README.md
            **/docs/**